### ISSUE TITLE
Connect database with home/movies page

### ISSUE THREAD

**Issue by chooseanother** [chooseanother/SEP6-MSDB#31]
Show 5 movies randomly selected within the last year in the carousel
- [x] Select x (5?) random movies from database, movies from current year
- [x] Get information from database for the x movies
- [x] Generate a list whit needed information
- [x] Add list to context
- [x] In html template, generate html elements from the list in context

Select n random movies (later should be based on user ratings) - top 10?
- [x] Select n random movies from database
- [x] add list of movies to context
- [x] In html template, generate html elements from the list in context

**Comment by 304125** [comment]
The top 10 best rated movies are not taken correctly for now as ratings are not implemented. Also, their rating is hard-code.
